services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes: # Grafana provisioning
      - ./docker/grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy" ]
      start_period: 10s
      start_interval: 1s
    ports:
      - "9090:9090"

  hcloud_exporter:
    image: promhippie/hcloud-exporter:latest
    restart: always
    environment:
      - HCLOUD_EXPORTER_TOKEN=<HCLOUD_TOKEN>
      - HCLOUD_EXPORTER_LOG_PRETTY=true
      - HCLOUD_EXPORTER_COLLECTOR_SERVER_METRICS=true
      - HCLOUD_EXPORTER_COLLECTOR_VOLUMES=true