version: "3"

services:
  grafana-lgtm:
    image: grafana/otel-lgtm
    ports: # Grafana UI
      - "3000:3000"
      # OpenTelemetry gRPC endpoint
      - "4317:4317"
      # OpenTelemetry HTTP endpoint
      - "4318:4318"
    environment: # Allow anonymous access to the Grafana UI
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"

  lwa-service:
    depends_on:
      - grafana-lgtm
    build:
        context: .
        dockerfile: lwa.Dockerfile
    ports:
        - "8080:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana-lgtm:4317"
      PORT: 80880